name: myhelper
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

   # For Nepali Date Picker
  nepali_date_picker: any
  # For QR Code Scanner
  qr_code_scanner: any
  # For Time Ago
  timeago: ^3.2.2
  # For Share Preference
  shared_preferences: ^2.0.15  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
 

  # # Custom Widget
  # myhelper:
  #   git:
  #     url: https://github.com/Saw2110/MyHelper-Flutter.git
  #     ref: main # branch name
